POST http://localhost:8080/validate
Content-Type: application/json

{
  "provider": "provider",
  "amount": 751234,
  "currency": "RUB",
  "date": "2025-10-10"
}

###

POST http://localhost:8080/validate
Content-Type: application/json

{
"provider": "provider",
"amount": 10000,
"currency": "USD",
"date": "2025-10-10"
}

### Получение курса валюты через мок ЦБ
GET http://localhost:8080/cbr?currency=USD&date=2025-10-21
Accept: application/json

###

GET http://localhost:8080/cbr?currency=EUR
Accept: application/json

###

GET http://localhost:8080/cbr?currency=RUB
Accept: application/json

###

GET http://localhost:8080/cbr
Accept: application/json

###
GET http://localhost:8080/cbr?currency=RUB&date=2025-10-21
Accept: application/json
