# Проверка платежа в рублях
POST http://localhost:8080/validate
Content-Type: application/json

{
  "provider": "provider",
  "amount": 751234,
  "currency": "RUB",
  "date": "2025-10-10"
}

### Получение курса валюты через мок ЦБ (пример USD)
GET http://localhost:8080/cbr?currency=USD&date=2025-10-21
Accept: application/json

### Получение курса EUR
GET http://localhost:8080/cbr?currency=EUR&date=2025-10-21
Accept: application/json


### Через xml
GET http://localhost:8080/cbr?currency=USD&date=2025-10-21
Accept: application/xml
