// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/proto/payment_checker.proto

package grpcapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePaymentRequest) Reset() {
	*x = ValidatePaymentRequest{}
	mi := &file_api_proto_payment_checker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePaymentRequest) ProtoMessage() {}

func (x *ValidatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_checker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePaymentRequest.ProtoReflect.Descriptor instead.
func (*ValidatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_checker_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatePaymentRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ValidatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ValidatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ValidatePaymentRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ValidatePaymentResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Allowed           bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	TotalRubInKopecks int64                  `protobuf:"varint,2,opt,name=total_rub_in_kopecks,json=totalRubInKopecks,proto3" json:"total_rub_in_kopecks,omitempty"`
	Reason            string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ValidatePaymentResponse) Reset() {
	*x = ValidatePaymentResponse{}
	mi := &file_api_proto_payment_checker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePaymentResponse) ProtoMessage() {}

func (x *ValidatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_payment_checker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePaymentResponse.ProtoReflect.Descriptor instead.
func (*ValidatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_payment_checker_proto_rawDescGZIP(), []int{1}
}

func (x *ValidatePaymentResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *ValidatePaymentResponse) GetTotalRubInKopecks() int64 {
	if x != nil {
		return x.TotalRubInKopecks
	}
	return 0
}

func (x *ValidatePaymentResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_api_proto_payment_checker_proto protoreflect.FileDescriptor

const file_api_proto_payment_checker_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/proto/payment_checker.proto\x12\x0epaymentchecker\"|\n" +
	"\x16ValidatePaymentRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\"|\n" +
	"\x17ValidatePaymentResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12/\n" +
	"\x14total_rub_in_kopecks\x18\x02 \x01(\x03R\x11totalRubInKopecks\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason2m\n" +
	"\x0ePaymentChecker\x12[\n" +
	"\bValidate\x12&.paymentchecker.ValidatePaymentRequest\x1a'.paymentchecker.ValidatePaymentResponseB\"Z internal/adapter/grpcapi;grpcapib\x06proto3"

var (
	file_api_proto_payment_checker_proto_rawDescOnce sync.Once
	file_api_proto_payment_checker_proto_rawDescData []byte
)

func file_api_proto_payment_checker_proto_rawDescGZIP() []byte {
	file_api_proto_payment_checker_proto_rawDescOnce.Do(func() {
		file_api_proto_payment_checker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_payment_checker_proto_rawDesc), len(file_api_proto_payment_checker_proto_rawDesc)))
	})
	return file_api_proto_payment_checker_proto_rawDescData
}

var file_api_proto_payment_checker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_payment_checker_proto_goTypes = []any{
	(*ValidatePaymentRequest)(nil),  // 0: paymentchecker.ValidatePaymentRequest
	(*ValidatePaymentResponse)(nil), // 1: paymentchecker.ValidatePaymentResponse
}
var file_api_proto_payment_checker_proto_depIdxs = []int32{
	0, // 0: paymentchecker.PaymentChecker.Validate:input_type -> paymentchecker.ValidatePaymentRequest
	1, // 1: paymentchecker.PaymentChecker.Validate:output_type -> paymentchecker.ValidatePaymentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_payment_checker_proto_init() }
func file_api_proto_payment_checker_proto_init() {
	if File_api_proto_payment_checker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_payment_checker_proto_rawDesc), len(file_api_proto_payment_checker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_payment_checker_proto_goTypes,
		DependencyIndexes: file_api_proto_payment_checker_proto_depIdxs,
		MessageInfos:      file_api_proto_payment_checker_proto_msgTypes,
	}.Build()
	File_api_proto_payment_checker_proto = out.File
	file_api_proto_payment_checker_proto_goTypes = nil
	file_api_proto_payment_checker_proto_depIdxs = nil
}
