// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/paymentchecker/v1/payment_checker.proto

package paymentcheckerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationReason int32

const (
	ValidationReason_VALIDATION_REASON_UNSPECIFIED ValidationReason = 0
	ValidationReason_OK                            ValidationReason = 1
	ValidationReason_RATE_UNAVAILABLE              ValidationReason = 2
	ValidationReason_LIMIT_EXCEEDED                ValidationReason = 3
)

// Enum value maps for ValidationReason.
var (
	ValidationReason_name = map[int32]string{
		0: "VALIDATION_REASON_UNSPECIFIED",
		1: "OK",
		2: "RATE_UNAVAILABLE",
		3: "LIMIT_EXCEEDED",
	}
	ValidationReason_value = map[string]int32{
		"VALIDATION_REASON_UNSPECIFIED": 0,
		"OK":                            1,
		"RATE_UNAVAILABLE":              2,
		"LIMIT_EXCEEDED":                3,
	}
)

func (x ValidationReason) Enum() *ValidationReason {
	p := new(ValidationReason)
	*p = x
	return p
}

func (x ValidationReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationReason) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_paymentchecker_v1_payment_checker_proto_enumTypes[0].Descriptor()
}

func (ValidationReason) Type() protoreflect.EnumType {
	return &file_proto_paymentchecker_v1_payment_checker_proto_enumTypes[0]
}

func (x ValidationReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationReason.Descriptor instead.
func (ValidationReason) EnumDescriptor() ([]byte, []int) {
	return file_proto_paymentchecker_v1_payment_checker_proto_rawDescGZIP(), []int{0}
}

type ValidatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePaymentRequest) Reset() {
	*x = ValidatePaymentRequest{}
	mi := &file_proto_paymentchecker_v1_payment_checker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePaymentRequest) ProtoMessage() {}

func (x *ValidatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paymentchecker_v1_payment_checker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePaymentRequest.ProtoReflect.Descriptor instead.
func (*ValidatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_paymentchecker_v1_payment_checker_proto_rawDescGZIP(), []int{0}
}

func (x *ValidatePaymentRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ValidatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ValidatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ValidatePaymentRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type ValidatePaymentResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Allowed           bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	TotalRubInKopecks int64                  `protobuf:"varint,2,opt,name=total_rub_in_kopecks,json=totalRubInKopecks,proto3" json:"total_rub_in_kopecks,omitempty"`
	Reason            ValidationReason       `protobuf:"varint,3,opt,name=reason,proto3,enum=paymentchecker.v1.ValidationReason" json:"reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ValidatePaymentResponse) Reset() {
	*x = ValidatePaymentResponse{}
	mi := &file_proto_paymentchecker_v1_payment_checker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePaymentResponse) ProtoMessage() {}

func (x *ValidatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_paymentchecker_v1_payment_checker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePaymentResponse.ProtoReflect.Descriptor instead.
func (*ValidatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_paymentchecker_v1_payment_checker_proto_rawDescGZIP(), []int{1}
}

func (x *ValidatePaymentResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *ValidatePaymentResponse) GetTotalRubInKopecks() int64 {
	if x != nil {
		return x.TotalRubInKopecks
	}
	return 0
}

func (x *ValidatePaymentResponse) GetReason() ValidationReason {
	if x != nil {
		return x.Reason
	}
	return ValidationReason_VALIDATION_REASON_UNSPECIFIED
}

var File_proto_paymentchecker_v1_payment_checker_proto protoreflect.FileDescriptor

const file_proto_paymentchecker_v1_payment_checker_proto_rawDesc = "" +
	"\n" +
	"-proto/paymentchecker/v1/payment_checker.proto\x12\x11paymentchecker.v1\"|\n" +
	"\x16ValidatePaymentRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date\"\xa1\x01\n" +
	"\x17ValidatePaymentResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12/\n" +
	"\x14total_rub_in_kopecks\x18\x02 \x01(\x03R\x11totalRubInKopecks\x12;\n" +
	"\x06reason\x18\x03 \x01(\x0e2#.paymentchecker.v1.ValidationReasonR\x06reason*g\n" +
	"\x10ValidationReason\x12!\n" +
	"\x1dVALIDATION_REASON_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\x14\n" +
	"\x10RATE_UNAVAILABLE\x10\x02\x12\x12\n" +
	"\x0eLIMIT_EXCEEDED\x10\x032s\n" +
	"\x0ePaymentChecker\x12a\n" +
	"\bValidate\x12).paymentchecker.v1.ValidatePaymentRequest\x1a*.paymentchecker.v1.ValidatePaymentResponseBBZ@payment-checker/internal/grpc/paymentchecker/v1;paymentcheckerv1b\x06proto3"

var (
	file_proto_paymentchecker_v1_payment_checker_proto_rawDescOnce sync.Once
	file_proto_paymentchecker_v1_payment_checker_proto_rawDescData []byte
)

func file_proto_paymentchecker_v1_payment_checker_proto_rawDescGZIP() []byte {
	file_proto_paymentchecker_v1_payment_checker_proto_rawDescOnce.Do(func() {
		file_proto_paymentchecker_v1_payment_checker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_paymentchecker_v1_payment_checker_proto_rawDesc), len(file_proto_paymentchecker_v1_payment_checker_proto_rawDesc)))
	})
	return file_proto_paymentchecker_v1_payment_checker_proto_rawDescData
}

var file_proto_paymentchecker_v1_payment_checker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_paymentchecker_v1_payment_checker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_paymentchecker_v1_payment_checker_proto_goTypes = []any{
	(ValidationReason)(0),           // 0: paymentchecker.v1.ValidationReason
	(*ValidatePaymentRequest)(nil),  // 1: paymentchecker.v1.ValidatePaymentRequest
	(*ValidatePaymentResponse)(nil), // 2: paymentchecker.v1.ValidatePaymentResponse
}
var file_proto_paymentchecker_v1_payment_checker_proto_depIdxs = []int32{
	0, // 0: paymentchecker.v1.ValidatePaymentResponse.reason:type_name -> paymentchecker.v1.ValidationReason
	1, // 1: paymentchecker.v1.PaymentChecker.Validate:input_type -> paymentchecker.v1.ValidatePaymentRequest
	2, // 2: paymentchecker.v1.PaymentChecker.Validate:output_type -> paymentchecker.v1.ValidatePaymentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_paymentchecker_v1_payment_checker_proto_init() }
func file_proto_paymentchecker_v1_payment_checker_proto_init() {
	if File_proto_paymentchecker_v1_payment_checker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_paymentchecker_v1_payment_checker_proto_rawDesc), len(file_proto_paymentchecker_v1_payment_checker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_paymentchecker_v1_payment_checker_proto_goTypes,
		DependencyIndexes: file_proto_paymentchecker_v1_payment_checker_proto_depIdxs,
		EnumInfos:         file_proto_paymentchecker_v1_payment_checker_proto_enumTypes,
		MessageInfos:      file_proto_paymentchecker_v1_payment_checker_proto_msgTypes,
	}.Build()
	File_proto_paymentchecker_v1_payment_checker_proto = out.File
	file_proto_paymentchecker_v1_payment_checker_proto_goTypes = nil
	file_proto_paymentchecker_v1_payment_checker_proto_depIdxs = nil
}
