// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: proto/paymentchecker/v1/payment_checker.proto

package paymentcheckerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PaymentChecker_Validate_FullMethodName = "/paymentchecker.v1.PaymentChecker/Validate"
)

// PaymentCheckerClient is the client API for PaymentChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentCheckerClient interface {
	Validate(ctx context.Context, in *ValidatePaymentRequest, opts ...grpc.CallOption) (*ValidatePaymentResponse, error)
}

type paymentCheckerClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentCheckerClient(cc grpc.ClientConnInterface) PaymentCheckerClient {
	return &paymentCheckerClient{cc}
}

func (c *paymentCheckerClient) Validate(ctx context.Context, in *ValidatePaymentRequest, opts ...grpc.CallOption) (*ValidatePaymentResponse, error) {
	out := new(ValidatePaymentResponse)
	err := c.cc.Invoke(ctx, PaymentChecker_Validate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentCheckerServer is the server API for PaymentChecker service.
// All implementations must embed UnimplementedPaymentCheckerServer
// for forward compatibility
type PaymentCheckerServer interface {
	Validate(context.Context, *ValidatePaymentRequest) (*ValidatePaymentResponse, error)
	mustEmbedUnimplementedPaymentCheckerServer()
}

// UnimplementedPaymentCheckerServer must be embedded to have forward compatible implementations.
type UnimplementedPaymentCheckerServer struct {
}

func (UnimplementedPaymentCheckerServer) Validate(context.Context, *ValidatePaymentRequest) (*ValidatePaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedPaymentCheckerServer) mustEmbedUnimplementedPaymentCheckerServer() {}

// UnsafePaymentCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentCheckerServer will
// result in compilation errors.
type UnsafePaymentCheckerServer interface {
	mustEmbedUnimplementedPaymentCheckerServer()
}

func RegisterPaymentCheckerServer(s grpc.ServiceRegistrar, srv PaymentCheckerServer) {
	s.RegisterService(&PaymentChecker_ServiceDesc, srv)
}

func _PaymentChecker_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatePaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentCheckerServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentChecker_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentCheckerServer).Validate(ctx, req.(*ValidatePaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentChecker_ServiceDesc is the grpc.ServiceDesc for PaymentChecker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentChecker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paymentchecker.v1.PaymentChecker",
	HandlerType: (*PaymentCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _PaymentChecker_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paymentchecker/v1/payment_checker.proto",
}
