definitions:
  httpapi.CBRRateResponse:
    properties:
      char_code:
        type: string
      date:
        type: string
      nominal:
        type: integer
      value_scaled:
        type: integer
    type: object
  httpapi.ValidatePaymentRequest:
    properties:
      amount:
        type: integer
      currency:
        type: string
      date:
        type: string
      provider:
        type: string
    type: object
  httpapi.ValidatePaymentResponse:
    properties:
      allowed:
        type: boolean
      reason:
        type: string
      totalRUBInKopecks:
        type: integer
    type: object
info:
  contact: {}
paths:
  /cbr:
    get:
      consumes:
      - application/json
      - text/xml
      description: Returns the rate for a given currency and date from the mock CBR
        service
      parameters:
      - description: Currency code
        in: query
        name: currency
        required: true
        type: string
      - description: Date in YYYY-MM-DD format
        in: query
        name: date
        type: string
      produces:
      - application/json
      - text/xml
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpapi.CBRRateResponse'
        "400":
          description: Bad request
          schema:
            type: string
        "404":
          description: Rate not found
          schema:
            type: string
      summary: Get currency rate
      tags:
      - cbr
  /validate:
    post:
      consumes:
      - application/json
      description: Validates a payment request with amount, currency, and date
      parameters:
      - description: Payment request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/httpapi.ValidatePaymentRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/httpapi.ValidatePaymentResponse'
        "400":
          description: Bad request
          schema:
            type: string
      summary: Validate foreign payment
      tags:
      - payments
swagger: "2.0"
